#@host = https://hackathon-ccr.herokuapp.com
@host = http://localhost:8001

# @name login
POST {{host}}/api/login  HTTP/1.1
content-type: application/json
accept: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "email": "david.meth@hotmail.com",
    "password": "123123123",
    "remember_me": true
}
######
# @name login
POST {{host}}/api/login  HTTP/1.1
content-type: application/json
accept: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "email": "itaal1a@email.com",
    "password": "123123123",
    "remember_me": true
}
######
@token = {{login.response.body.success.token}}
######
# Novo Usuário
POST {{host}}/api/company/register  HTTP/1.1
content-type: application/json
accept: application/json

{
    "name":"Italo",
    "email":"itaal1a@email.com",

    "password": "123123123",
    "c_password": "123123123",
    "industry":"random stuff",
    "employees_number":"30"
}
#############

######
# Novo Usuário
POST {{host}}/api/person/register  HTTP/1.1
content-type: application/json
accept: application/json

{
    "name":"David Meth",
    "email":"david.meth@hotmail.com",
    "cpf":"011.111.115-79",
    "occupation_area":"random",
    "birth":"1990-12-13",
    "number":"(71)33569897",
    "password": "123123123",
    "educational_level":"5",
    "c_password": "123123123"
}
#############

#############
# Teste de Login
GET {{host}}/api/test-auth  HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Bearer {{token}}
#########
# @name login
POST {{host}}/api/login  HTTP/1.1
content-type: application/json
accept: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "email": "david.meth@hotmail.com",
    "password": "123123123",
    "remember_me": true
}
######
# @name login
POST {{host}}/api/login  HTTP/1.1
content-type: application/json
accept: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "email": "itaal1a@email.com",
    "password": "123123123",
    "remember_me": true
}
#############
# Teste de Login
GET {{host}}/api/index  HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Bearer {{token}}



insert into trails values (default,'Trilha 2','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum',now(),now()),
(default,'Trilha 3','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum',now(),now());

insert into courses values
(default,'Curso 4','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',3,now(),now()),
(default,'Curso 5','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',3,now(),now()),
(default,'Curso 4','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',2,now(),now()),
(default,'Curso 5','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',2,now(),now()),
(default,'Curso 6','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',2,now(),now()),
(default,'Curso 7','Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum Lorem Ipssum','15 min',2,now(),now());



insert into lessons values
(default, 'Lição 1','Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1',1,now(),now()),
(default, 'Lição 2','Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2',1,now(),now()),
(default, 'Lição 3','Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3',1,now(),now()),
(default, 'Lição 1','Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1',2,now(),now()),
(default, 'Lição 2','Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2',2,now(),now()),
(default, 'Lição 3','Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3',2,now(),now()),
(default, 'Lição 1','Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1 Conteúdo da Lição 1',3,now(),now()),
(default, 'Lição 2','Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2 Conteúdo da Lição 2',3,now(),now()),
(default, 'Lição 3','Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3 Conteúdo da Lição 3',3,now(),now());


insert into tests values (default,'Teste do Curso 1','Alternativa A','Alternativa B','Alternativa C',null,null,'Alternativa A',now(),now(),1),
(default,'Teste do Curso 2','Alternativa A','Alternativa B','Alternativa C',null,null,'Alternativa A',now(),now(),2),
(default,'Teste do Curso 3','Alternativa A','Alternativa B','Alternativa C',null,null,'Alternativa A',now(),now(),3);


insert into lesson_person values (default,1,1,now(),now()),(default,1,2,now(),now()),(default,1,3,now(),now()),(default,1,4,now(),now());


insert into person_test_tries values (default,1,1,1,now(),now());
